[workspace]
resolver = "2"

members = [
    "libraries/standard",
    "libraries/third-party",
    "books/Webアプリ開発で学ぶRust言語入門/my-todo",
]

[workspace.package]
version = "0.1.0"
authors = ["kuwata0037 <kuwata0037@gmail.com>"]
edition = "2021"
