CREATE TABLE label
(
    id      SERIAL  PRIMARY KEY,
    name    TEXT    NOT NULL
);

CREATE TABLE todo_labels
(
    id SERIAL PRIMARY KEY,
    todo_id     INTEGER NOT NULL REFERENCES todo    (id) DEFERRABLE INITIALLY DEFERRED,
    label_id    INTEGER NOT NULL REFERENCES label   (id) DEFERRABLE INITIALLY DEFERRED
);
